### ISSUE TITLE
TAL-Chorus is not an instrument

### ISSUE THREAD

**Issue by derkrasseleo** [studiorack/studiorack-registry#1]
TAL-Chorus v1.6.0 is listed as a instrument and I can't seem to find where to change that.

**Comment by kmturley** [comment]
Great find!

You can find out the source GitHub repo by looking at the url or plugin id:
https://studiorack.github.io/studiorack-site/instruments/studiorack/distrho-ports/tal-chorus

Maps to this repo:
https://github.com/studiorack/distrho-ports

The release is here:
https://github.com/studiorack/distrho-ports/releases/tag/v1.0.0

Inside the release is a `plugins.json` file containing all the metadata used for StudioRack:
https://github.com/studiorack/distrho-ports/releases/download/v1.0.0/plugins.json

I've updated TAL-Chorus to be an Effect.
Thanks!
