### ISSUE TITLE
how do i format the .json for a repo with multiple plugins?

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-registry#4]
https://github.com/zamaudio/zam-plugins/issues/103

zamaudio wants to integrate but ive no idea how i add multiple plugins to

{
  "plugins": [
    {
      "author": "Your Name",
      "homepage": "https://www.yoursite.com",
      "name": "Your Plugin Name",
      "description": "Test Class",
      "tags": [
        "Fx",
        "Delay"
      ],
      "version": "1.1.0",
      "id": "your-plugin",
      "date": "2020-12-09T17:25:12.081Z",
      "files": {
        "audio": {
          "name": "your-plugin.wav",
          "size": 352844
        },
        "image": {
          "name": "your-plugin.png",
          "size": 35091
        },
        "linux": {
          "name": "your-plugin-linux.zip",
          "size": 13089625
        },
        "mac": {
          "name": "your-plugin-mac.zip",
          "size": 13089625
        },
        "win": {
          "name": "your-plugin-win.zip",
          "size": 13089625
        }
      }
    }
  ]
}

**Comment by kmturley** [comment]
plugins is an array in json
```
plugins: []
```

This means you can add multiple plugins like this:
```
plugins: [
  { "author": "a" },
  { "author": "b" },
  { "author": "c" }
]
```

Here is an example of a single github repo containing multiple plugins:
https://github.com/studiorack/iem-plugin-suite/releases/tag/v1.13.0

Look at the plugins.json to see how it was implemented!

**Comment by RustoMCSpit** [comment]
could you write this one for the zamaudio folk cause im ngl it's a bit confusing for me https://github.com/zamaudio/zam-plugins/issues/103
