### ISSUE TITLE
there should be a list of different tags in the read.me, as well as a standardised way of ordering them

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-registry#5]

**Comment by kmturley** [comment]
Technically folks can add any tags they want at the moment.

However the website, app and cli will only show these tags
https://github.com/studiorack/studiorack-core/blob/main/src/config-defaults.ts#L276

I could make that more explicit though. So agree with this request.

**Comment by kmturley** [comment]
This commit updates the README with a list of tags which should be used:
https://github.com/studiorack/studiorack-registry/commit/32c90809f11e6c8d7ecf3bc7d54982bb9a856e55
