### ISSUE TITLE
Expand plugin metadata with additional fields

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-registry#6]

**Comment by RustoMCSpit** [comment]
i asked chatgpt what else it should store, some of it's garbage but heres what it said verbatim:

    Compatibility and System Requirements
        OS requirements (e.g., Windows 10 or later, macOS 10.13 or later, etc.)
        Hardware requirements (e.g., CPU, memory, disk space)
        Software dependencies (e.g., frameworks, libraries, specific versions of other software)

    Licensing and Legal Information
        License type (e.g., GPL, MIT, proprietary)
        Copyright details (e.g., "Copyright [year] [author name]")
        Terms of use or EULA (End User License Agreement)

    Installation and Setup Instructions
        Installation steps for different platforms
        Setup and configuration instructions

    Support and Contact Information
        Support email or contact form
        Documentation links or user manuals
        Community forums or other support resources

    Changelog and Version History
        Details of changes in each version
        Release dates for different versions

    Author and Contributor Information
        List of contributors
        Links to social media, GitHub, or other profiles
        Acknowledgments or credits for third-party contributions

    Additional Resources
        Links to tutorials or examples
        Links to YouTube or other media showcasing the plugin
        Testimonials or reviews

    Security Information
        Information on security practices or audits
        Vulnerability disclosures or known issues

**Comment by kmturley** [comment]
Here is the current json metadata:
https://studiorack.github.io/studiorack-registry/

Regarding your list:
- Compatibility and System Requirements - Currently all plugins are Linux, Mac and Windows 64 bit, so I omitted this information. I will add though If this is expanded to plugins which don't build for all platforms as 64 bit

- Licensing and Legal Information - I already pull the license information from the GitHub repo, but it has to be set on the repo itself: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

- Installation and Setup Instructions - Installation steps should be the same regardless of system of platform. That's one things I am aiming to do with this project! 

- Support and Contact Information -  I already list the author and link to the github repo, which should be sufficient to find support for a specific plugin.

- Changelog and Version History - json has each version based on release version numbers with the date. So I think this is already covered

- Author and Contributor Information - I already list the author and link to the github repo, which should be sufficient to find more information for a specific plugin.

- Additional Resources - I think this is out-of-scope at the moment for this project. I could in the future have videos or other supporting materials. But would want it to be useful and good quality to include it.

- Security Information - I could do more here. Definitely an area to investigate

So out of these points I think these two warrant further improvment:
1) Compatibility and System Requirements
2) Security Information

**Comment by RustoMCSpit** [comment]
> Compatibility and System Requirements - Currently all plugins are Linux, Mac and Windows 64 bit, so I omitted this information. I will add though If this is expanded to plugins which don't build for all platforms as 64 bit

this was discussed by Ardura in the discord

**Comment by RustoMCSpit** [comment]
> Licensing and Legal Information - I already pull the license information from the GitHub repo, but it has to be set on the repo itself: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

with the new yaml approach does this still apply

**Comment by RustoMCSpit** [comment]
> Security Information

this should include if the build is reproducible

**Comment by kmturley** [comment]
This feature has been built into the new registry at: https://github.com/open-audio-stack/open-audio-stack-registry
