### ISSUE TITLE
 have a build pipeline

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-registry#7]
Provide a script and/or a GitHub action step
But first have a definition of what you want and where you want it

**Comment by kmturley** [comment]
There is already a build pipeline here:
https://github.com/studiorack/studiorack-registry/blob/main/.github/workflows/release.yml

You can view the pipeline runs here:
https://github.com/studiorack/studiorack-registry/actions

The result is deployed to GitHub pages here:
https://github.com/studiorack/studiorack-registry/tree/gh-pages

**Comment by RustoMCSpit** [comment]
> There is already a build pipeline here: https://github.com/studiorack/studiorack-registry/blob/main/.github/workflows/release.yml
> 
> You can view the pipeline runs here: https://github.com/studiorack/studiorack-registry/actions
> 
> The result is deployed to GitHub pages here: https://github.com/studiorack/studiorack-registry/tree/gh-pages

im confused, the surge team said my PR was wrong? https://github.com/jatinchowdhury18/AnalogTapeModel/pull/317 is it wrong?
